version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack-pro  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    environment:
      # Activate LocalStack Pro: https://docs.localstack.cloud/getting-started/auth-token/
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:-ls-rARuNeMo-LayI-DUMa-3592-CeWE09578a11}  # required for Pro
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - PERSISTENCE=${PERSISTENCE:-0}
      - PROVIDER_OVERRIDE_LAMBDA=v2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      ls:

  ops:
    container_name: ops
    working_dir: /code/tf
    build:
      context: .
      dockerfile: Dockerfile.ops
    depends_on: 
      - localstack
    entrypoint: "/bin/bash"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
      - S3_HOSTNAME=localstack
      - AWS_ENDPOINT_URL_S3=http://localstack:4566
    volumes:
      - .:/code
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ls

networks:
  ls:
