# generated by datamodel-codegen:
#   filename:  awseventv2.json
#   timestamp: 2024-04-06T16:10:00+00:00

from typing import Literal
from pydantic import BaseModel


class Validity(BaseModel):
    notBefore: str
    notAfter: str


class ClientCert(BaseModel):
    clientCertPem: str
    subjectDN: str
    issuerDN: str
    serialNumber: str
    validity: Validity


class Authentication(BaseModel):
    clientCert: ClientCert


class Jwt(BaseModel):
    claims: dict
    scopes: list[str]


class Authorizer(BaseModel):
    jwt: Jwt


class Http(BaseModel):
    method: str
    path: str
    protocol: str | None = None
    sourceIp: str | None = None
    userAgent: str | None = None


class RequestContext(BaseModel):
    accountId: str | None = None
    apiId: str | None = None
    authentication: Authentication | None = None
    authorizer: Authorizer | None = None
    domainName: str | None = None
    domainPrefix: str | None = None
    http: Http
    requestId: str | None = None
    routeKey: str | None = None
    stage: str | None = None
    time: str | None = None
    timeEpoch: int | None = None


class EventV2(BaseModel):
    version: Literal["2.0"]
    routeKey: str | None = None
    rawPath: str
    rawQueryString: str
    cookies: list[str] | None = None
    headers: dict
    queryStringParameters: dict
    requestContext: RequestContext
    body: str | None = None
    pathParameters: dict | None = None
    isBase64Encoded: bool = False
    stageVariables: dict | None = None
