# generated by datamodel-codegen:
#   filename:  awseventv2.json
#   timestamp: 2024-04-06T16:10:00+00:00

from typing import Any, Literal

from pydantic import BaseModel


class Validity(BaseModel):
    notBefore: str | None = None
    notAfter: str | None = None


class ClientCert(BaseModel):
    clientCertPem: str | None = None
    subjectDN: str | None = None
    issuerDN: str | None = None
    serialNumber: str | None = None
    validity: Validity | None = None


class Authentication(BaseModel):
    clientCert: ClientCert | None = None


class Jwt(BaseModel):
    claims: dict | None = None
    scopes: list[str] | None = None


class Authorizer(BaseModel):
    jwt: Jwt | None = None


class Http(BaseModel):
    method: str
    path: str
    protocol: str | None = None
    sourceIp: str | None = None
    userAgent: str | None = None


class RequestContext(BaseModel):
    accountId: str | None = None
    apiId: str | None = None
    authentication: Authentication | None = None
    authorizer: Authorizer | None = None
    domainName: str | None = None
    domainPrefix: str | None = None
    http: Http
    requestId: str | None = None
    routeKey: str | None = None
    stage: str | None = None
    time: str | None = None
    timeEpoch: int | None = None


class EventV2(BaseModel):
    version: Literal["2.0"]
    routeKey: str | None = None
    rawPath: str | None = None
    rawQueryString: str
    cookies: list[str] | None = None
    headers: dict | None = None
    queryStringParameters: dict | None = None
    requestContext: RequestContext
    body: Any | None = None
    pathParameters: dict | None = None
    isBase64Encoded: bool = False
    stageVariables: dict | None = None
