# generated by datamodel-codegen:
#   filename:  awseventv1.json
#   timestamp: 2024-04-06T16:10:15+00:00

from typing import Any, Literal

from pydantic import BaseModel


class Authorizer(BaseModel):
    claims: dict | None = None
    scopes: dict | None = None


class Validity(BaseModel):
    notBefore: str | None = None
    notAfter: str | None = None


class ClientCert(BaseModel):
    clientCertPem: str | None = None
    subjectDN: str | None = None
    issuerDN: str | None = None
    serialNumber: str | None = None
    validity: Validity | None = None


class Identity(BaseModel):
    accessKey: str | None = None
    accountId: str | None = None
    caller: str | None = None
    cognitoAuthenticationProvider: str | None = None
    cognitoAuthenticationType: str | None = None
    cognitoIdentityId: str | None = None
    cognitoIdentityPoolId: str | None = None
    principalOrgId: str | None = None
    sourceIp: str | None = None
    user: str | None = None
    userAgent: str | None = None
    userArn: str | None = None
    clientCert: ClientCert | None = None


class RequestContext(BaseModel):
    accountId: str | None = None
    apiId: str | None = None
    authorizer: Authorizer | None = None
    domainName: str | None = None
    domainPrefix: str | None = None
    extendedRequestId: str | None = None
    httpMethod: str | None = None
    identity: Identity | None = None
    path: str | None = None
    protocol: str | None = None
    requestId: str | None = None
    requestTime: str | None = None
    requestTimeEpoch: int | None = None
    resourceId: str | None = None
    resourcePath: str | None = None
    stage: str | None = None


class EventV1(BaseModel):
    version: Literal["1.0"]
    resource: str | None = None
    path: str | None = None
    httpMethod: str | None = None
    headers: dict | None = None
    multiValueHeaders: dict | None = None
    queryStringParameters: dict | None = None
    multiValueQueryStringParameters: dict | None = None
    requestContext: RequestContext | None = None
    pathParameters: dict | None = None
    stageVariables: dict | None = None
    body: Any | None = None
    isBase64Encoded: bool = False
    ## Trilodocs added
    authorizationToken: str | None = None
    methodArn: str | None = None
