# generated by datamodel-codegen:
#   filename:  awseventv1.json
#   timestamp: 2024-04-06T16:10:15+00:00

from typing import Any

from pydantic import BaseModel


class Authorizer(BaseModel):
    scope: str | None = None
    principalId: str | None = None
    integrationLatency: int | None = None


class RequestContext(BaseModel):
    accountId: str | None = None
    apiId: str | None = None
    authorizer: Authorizer | None = None
    domainName: str | None = None
    domainPrefix: str | None = None
    extendedRequestId: str | None = None
    httpMethod: str | None = None
    identity: dict | None = None
    path: str | None = None
    protocol: str | None = None
    requestId: str | None = None
    requestTime: str | None = None
    requestTimeEpoch: int | None = None
    resourceId: str | None = None
    resourcePath: str | None = None
    stage: str | None = None


class EventV1(BaseModel):
    resource: str | None = None
    path: str | None = None
    httpMethod: str | None = None
    headers: dict | None = None
    multiValueHeaders: dict | None = None
    queryStringParameters: dict | None = None
    multiValueQueryStringParameters: dict | None = None
    requestContext: RequestContext | None = None
    pathParameters: dict | None = None
    stageVariables: dict | None = None
    body: Any | None = None
    isBase64Encoded: bool = False
    authorizationToken: str | None = None
    methodArn: str | None = None
